import './globals.css'
import { Inter, Poppins } from 'next/font/google'
import Header from '@/components/header'
import Sidebar from '@/components/sidebar'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({subsets: ["latin"], weight:['100', '200', '300']}) 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning={true}>
        <Header/>
        <Sidebar/>
        {children}
      </body>
    </html>
  )
}
